// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from MELCodes.djinni

#import "MRSize.h"
#import <Foundation/Foundation.h>

@interface MRAlgorithmOptions : NSObject
- (nonnull instancetype)initWithCannyLow:(int32_t)cannyLow
                               cannyHigh:(int32_t)cannyHigh
                           cannyAperture:(int32_t)cannyAperture
                                 cannyL2:(BOOL)cannyL2
                           prefilterSize:(nonnull MRSize *)prefilterSize
                       boxSideLimitRatio:(float)boxSideLimitRatio;
+ (nonnull instancetype)AlgorithmOptionsWithCannyLow:(int32_t)cannyLow
                                           cannyHigh:(int32_t)cannyHigh
                                       cannyAperture:(int32_t)cannyAperture
                                             cannyL2:(BOOL)cannyL2
                                       prefilterSize:(nonnull MRSize *)prefilterSize
                                   boxSideLimitRatio:(float)boxSideLimitRatio;

@property (nonatomic, readonly) int32_t cannyLow;

@property (nonatomic, readonly) int32_t cannyHigh;

@property (nonatomic, readonly) int32_t cannyAperture;

@property (nonatomic, readonly) BOOL cannyL2;

@property (nonatomic, readonly, nonnull) MRSize * prefilterSize;

@property (nonatomic, readonly) float boxSideLimitRatio;

@end
