// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from MELCodes.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, MRDataFormat)
{
    MRDataFormatUNKNOWN,
    MRDataFormatJPEG,
    MRDataFormatGRAY8,
    MRDataFormatRGBA8888,
};
