// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from MELCodes.djinni

#import "MRPoint.h"
#import <Foundation/Foundation.h>

@interface MRDetectedCode : NSObject
- (nonnull instancetype)initWithValue:(int32_t)value
                              contour:(nonnull NSArray<MRPoint *> *)contour;
+ (nonnull instancetype)DetectedCodeWithValue:(int32_t)value
                                      contour:(nonnull NSArray<MRPoint *> *)contour;

@property (nonatomic, readonly) int32_t value;

@property (nonatomic, readonly, nonnull) NSArray<MRPoint *> * contour;

@end
