// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from MELCodes.djinni

#import "MRAlgorithmOptions.h"
#import "MRDetectedCode.h"
#import "MROptions.h"
#import "MRPoint.h"
#import "MRSize.h"
#import <Foundation/Foundation.h>
@class MRImageProcessor;
@protocol MRLogger;


@interface MRImageProcessor : NSObject

+ (nullable MRImageProcessor *)Create:(nonnull MROptions *)opts;

- (int32_t)Release;

- (void)SetAlgorithmOptions:(nonnull MRAlgorithmOptions *)opts;

- (nonnull MRAlgorithmOptions *)GetAlgorithmOptions;

- (void)SetLogger:(nullable id<MRLogger>)log;

- (nonnull NSArray<MRDetectedCode *> *)ProcessFrame:(nonnull NSData *)image
                                         extractAll:(BOOL)extractAll;

- (nonnull NSArray<MRDetectedCode *> *)ProcessSubFrame:(nonnull NSData *)image
                                               topLeft:(nonnull MRPoint *)topLeft
                                                  size:(nonnull MRSize *)size
                                            extractAll:(BOOL)extractAll;

- (void)SetDebugOutput:(nonnull NSString *)name;

@end
