// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from MELCodes.djinni

#import <Foundation/Foundation.h>


@protocol MRLogger

- (void)d:(nonnull NSString *)id
        s:(nonnull NSString *)s;

@end
