// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from MELCodes.djinni

#import <Foundation/Foundation.h>

@interface MRSize : NSObject
- (nonnull instancetype)initWithWidth:(int32_t)width
                               height:(int32_t)height;
+ (nonnull instancetype)SizeWithWidth:(int32_t)width
                               height:(int32_t)height;

@property (nonatomic, readonly) int32_t width;

@property (nonatomic, readonly) int32_t height;

@end
